name: replicate-cd

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      BASE_IMAGE: 'daanelson/real-esrgan-a100'
      PUSH_DEST: 'daanelson/real-esrgan-a100'

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: install yolo
      run: |
        sudo curl -o /usr/local/bin/yolo -L "https://github.com/replicate/yolo/releases/latest/download/yolo_$(uname -s)_$(uname -m)"
        sudo chmod +x /usr/local/bin/yolo

    - name: what changed
      id: files
      run: |
        FILES_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)
        echo "FILES_CHANGED=$FILES_CHANGED" >> $GITHUB_ENV

    - name: push model
      env:
       REPLICATE_API_TOKEN: ${{secrets.REPLICATE_API_TOKEN}}
       SENTRY_DSN: ${{secrets.SENTRY_DSN}}
      run: |
        echo "pushing changes from $BASE_IMAGE to $PUSH_DEST"
        echo "changed files: $FILES_CHANGED"
        yolo push -e SENTRY_DSN="$SENTRY_DSN" --base $BASE_IMAGE --dest $PUSH_DEST $FILES_CHANGED

    ## TODO once it exists - use deployments API to update appropriate deployment
