name: replicate-ci

on:
  pull_request:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      BASE_IMAGE: 'daanelson/real-esrgan-a100'
      PUSH_DEST: 'daanelson/real-esrgan-staging'
      TEST_ENDPOINT: 'https://replica'

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: what-changed
      id: files
      run: |
        FILES_CHANGED=$(git diff --name-only --diff-filter=AMR ${{ github.event.before }} ${{ github.event.after }} | xargs)
        echo "FILES_CHANGED=$FILES_CHANGED" >> $GITHUB_ENV
        if echo "$FILES_CHANGED" | grep -q 'cog.yaml'; then
            echo "::set-output name=cog_push::true"
          else
            echo "::set-output name=cog_push::false"
          fi

    # if cog.yaml changes - cog build and push. else - yolo build and push

    - name: setup-cog
      if: steps.what-changed.outputs.cog_push == 'true'
      uses: replicate/setup-cog@v1.0.2
      with:
        token: ${{ secrets.REPLICATE_API_TOKEN }}

    - name: cog-build
      if: steps.what-changed.outputs.cog_push == 'true'
      run: |
        cog build

    - name: cog-push
      if: steps.what-changed.outputs.cog_push == 'true'
      run: |
        cog push r8.im/"$PUSH_DEST"

    - name: install-yolo
      if: steps.what-changed.outputs.cog_push == 'false'
      run: |
        sudo curl -o /usr/local/bin/yolo -L "https://github.com/replicate/yolo/releases/latest/download/yolo_$(uname -s)_$(uname -m)"
        sudo chmod +x /usr/local/bin/yolo

    - name: push-model
      if: steps.what-changed.outputs.cog_push == 'false'
      env:
       REPLICATE_API_TOKEN: ${{secrets.REPLICATE_API_TOKEN}}
       SENTRY_DSN: ${{secrets.SENTRY_DSN}}
      run: |
        echo "pushing changes from $BASE_IMAGE to $PUSH_DEST"
        echo "changed files: $FILES_CHANGED"
        yolo push -e SENTRY_DSN="$SENTRY_DSN" --base $BASE_IMAGE --dest $PUSH_DEST $FILES_CHANGED

    # - name: test model
    #   -- just run some http tests
    #   -- borrow template from SDXL
    #   -- pass in some flag s.t. we're testing in prod
